-- Add score columns to tastings table
ALTER TABLE tastings
ADD COLUMN IF NOT EXISTS score_overall INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS score_farge INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS score_lukt INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS score_smak INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS score_friskhet INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS score_fylde INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS score_sodme INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS score_snaerp INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS score_alkohol INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS score_pris INTEGER DEFAULT 0;

-- Create index for querying by overall score
CREATE INDEX IF NOT EXISTS idx_tastings_score_overall ON tastings(score_overall);
